### ISSUE TITLE
Can not create token

### ISSUE THREAD

**Issue by codventdev01** [samir-hussein/paymob#1]
The token is not created by this PayMob::AuthenticationRequest() method, i have provided all required credentials in env file and also publish the paymob config. 

{#1195 ▼ // app/Http/Controllers/PayMobController.php:29
  +"detail": "Can not create token"
}

**Comment by samir-hussein** [comment]
can you send your project files?

**Comment by ahsan85** [comment]
I am facing same issue

**Comment by samir-hussein** [comment]
follow this tutorial https://www.youtube.com/watch?v=bRCZu9J8hWE&ab_channel=SamirHussein
